nelmio_cors:
  defaults:
    allow_origin: ["http://localhost:8090"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization"]
    max_age: 3600
  paths:
    "^/api/": # Applique CORS sur toutes les routes API
      allow_origin: ["http://localhost:8090"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_headers: ["Content-Type", "Authorization"]
      max_age: 3600
