# config/packages/nelmio_cors.yaml
nelmio_cors:
  defaults:
    allow_credentials: true # Autorise l'envoi des informations d'identification comme les cookies
    allow_origin: ["http://localhost:8090"]
    allow_methods: ["GET", "POST", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization"]
    max_age: 3600
  paths:
    "^/api/": # Applique CORS pour toutes les routes API
      allow_origin: ["http://localhost:8090"]
      allow_methods: ["GET", "POST", "OPTIONS"]
      allow_headers: ["Content-Type", "Authorization"]
      max_age: 3600
